// Login Admin User
POST http://localhost:9000/admin/auth
Content-Type: application/json

{
  "email": "admin@medusa-test.com",
  "password": "supersecret"
}

###

// Multi-Vendor Create Button (Creates 3 Users && sets store_id for products)
// Note: This should likely be a POST request if it modifies server state.
GET http://localhost:9000/admin/custom/user
Content-Type: application/json

###
GET http://localhost:9000/store/custom/products?store_name=Goblin Store
Content-Type: application/json

###


### Create a Wishlist
POST http://localhost:9000/wishlist
Content-Type: application/json

{
  "region_id": "reg_01HW241PHR9AN5HVQE876TNGPS",
  "customer_id": "cus_01HW298CJPT60818GCHWD8GAT7"
}
